soccer:
    build: .
    volumes:
        - keepaway/:/home/soccer/keepaway
        - agent/:/home/soccer/agent/src/agent
        - logs/:/home/soccer/logs
        # - .rcssserver:/home/soccer/.rcssserver
    command: /bin/bash  # CHANGE LATER
